name: List Versions of ECS With Default Region By KooCLI
on:
  push:
    branches:
        master-dev
jobs:
  List-Versions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2
      
      - name: Authenticate to Huawei Cloud
        uses: huaweicloud/auth-action@v1.0.0
        with: 
          access_key_id: ${{ secrets.ACCESSKEY }} 
          secret_access_key: ${{ secrets.SECRETACCESSKEY }}
          region: cn-north-4

      - name: Install KooCLI and List Versions Of ECS
        uses: huaweicloud/huaweicloud-cli-action@v1.0.2
          
      - name: echo KooCLI
        run: |
          hcloud version
          hcloud ECS NovaListVersions
